### ISSUE TITLE
Time Step Value Gone?

### ISSUE THREAD

**Issue by babbott1000** [wpilibsuite/PathWeaver#173]
In the 2020 version of PathWeaver, the Time Step(and Max Jerk) field(s) are omitted.  What is the reason behind this and how is the time step now calculated?  Is this adjustable somehow?  Am I missing something?

**Comment by prateekma** [comment]
There is no fixed time-step for trajectories anymore. A user can calculate the trajectory state at any time since the start of the trajectory, due to the way we interpolate between trajectory states.

The 2020 trajectory generation does not support jerk limiting, and therefore only generates trapezoid profiles. Jerk limiting is really not needed for drivetrains and a more comprehensive `DifferentialDriveDynamicsConstraint` exists for ensuring that drive dynamics are obeyed when generating a trajectory,
