### ISSUE TITLE
Images & json for the FRC BAE mini-bot challenges

### ISSUE THREAD

**Issue by david-lemasurier** [wpilibsuite/PathWeaver#211]
Can we get images and json for the Color Conundrum field?
https://wpilib.org/blog/bae-systems-mini-bot-challenge-2-color-conundrum

If not, any suggestions on how to create working images?

**Comment by sciencewhiz** [comment]
There's instructions for using your images here: https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/pathweaver/adding-field-images.html

**Comment by david-lemasurier** [comment]
I am aware of those instructions, however, when I use images that I create either the paths are not visible or they extend beyond the image.  I don't have this issue with the provided images.

**Comment by jasondaming** [comment]
Can you post the images and json files that you created?

**Comment by david-lemasurier** [comment]
[Color Conundrum Course 1.zip](https://github.com/wpilibsuite/PathWeaver/files/6192981/Color.Conundrum.Course.1.zip)

**Comment by jasondaming** [comment]
I added that to my games folder and it worked fine.  I agree that the default path went off the map because the scale of this is so high.  What I did was make an additional waypoint on the screen (click and drag on the line) and then saved and went to the path file and removed the last waypoint.

![image](https://user-images.githubusercontent.com/15695521/112234977-bb4f5700-8c0b-11eb-817e-736bf3090158.png)

I now understand the problem you are having better and I think in the future I will make the default path that is created be some % of the total area rather that a fixed distance.
