### ISSUE TITLE
A question about drawing a trajectory in PathWeaver

### ISSUE THREAD

**Issue by mendax1234** [wpilibsuite/PathWeaver#265]
**Describe the question you have.**
A clear and concise description of what you want clarification on.

- Out  team uses a swerve drive and we want to use Pahtweaver to draw the trajectory. But it seems that Pathweaver is designed for differential drive. However , some say that it can also be used in a swerve drive. So, my question is how to drive a trajectory for a swerve. For example , if l want to draw a bounce path. l should draw like below? 

![image](https://user-images.githubusercontent.com/62934294/135823182-e3d07e2d-a0f4-490f-9786-b5318e4587c6.png)

- Besides, how can l control the head of my robot?

**Describe the reason for your confusion.**
A clear and concise description of why the question requires clarification and what's confusing.

- First , what is the whole length of such the whole field. For instance, just take the picture above as an example . What is the length between the start zone and the finish zone? 
- Second, is this trajectory the same with the waypoint like the example code below:
```
  Trajectory exampleTrajectory =
      TrajectoryGenerator.generateTrajectory(
          // Start at the origin facing the +X direction
          new Pose2d(0, 0, new Rotation2d(0)),
          // Pass through these two interior waypoints, making an 's' curve path
          List.of(new Translation2d(1, 0), new Translation2d(2, -1)),
          // End 3 meters straight ahead of where we started, facing forward
          new Pose2d(3, 0, new Rotation2d(0)),
          config);
```

**Is your question related to a problem? Please describe.**

- Yeah , l am frustrate with the auto of swerve . After seeing the docs in WPILIB, l am still frustrated. For example, how is the 8.5 got using the P and D value from the characterization tool.

![image](https://user-images.githubusercontent.com/62934294/135824285-a188a5eb-73c5-44b4-9506-8959fb27510b.png)

**Additional context**
Add any other context or screenshots about the question here.

- At last , l wonder how to deploy the robot code in charavterization tool if l only can connect to the robot wifi. (l cannot connect to the Internet and RoboRio at the same time)

**Comment by jasondaming** [comment]
PathWeaver is designed for differential drive.  I have not personally used it for swerve but I know others have.

> So, my question is how to drive a trajectory for a swerve. For example , if l want to draw a bounce path. l should draw like below?

I think instead of one continuous path you would want to separate it into multiple paths.  This would allow the point turn that I think you want instead of a rounded turn (not sure how big the rounding would be in practice probably depends on your swerve) which is what I think you would get now.

> Besides, how can l control the head of my robot?

I don't think we can answer this without more information about how your robot is coded and what you are trying to do.

> First , what is the whole length of such the whole field. For instance, just take the picture above as an example . What is the length between the start zone and the finish zone?

The length of the field is whatever is setup for the field image you are using.  [Here](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/pathweaver/adding-field-images.html) is the article on setting up a custom field image you can see the length is specified.  In the case above the field is the [2021 at-home challenges](https://firstfrc.blob.core.windows.net/frc2021/Manual/AtHomeManualSections/2021AtHomeChallengesManualSection02.pdf) (see 2.4.4) which are 15' by 30'

> Second, is this trajectory the same with the waypoint like the example code below

You copied the example in the trajectory tutorial.  That is for manually specifying the waypoints.  To use PathWeaver you would [import the trajectory](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/pathweaver/integrating-robot-program.html) generated by PathWeaver

> For example, how is the 8.5 got using the P and D value from the characterization tool.

I actually opened an [issue](https://github.com/wpilibsuite/frc-docs/issues/953) for this problem a while back.  Unfortunately since the characterization tool is being replaced with the new SysID tool there hasn't been a lot of interest in updating this.

> At last , l wonder how to deploy the robot code in charavterization tool if l only can connect to the robot wifi. (l cannot connect to the Internet and RoboRio at the same time)

I don't understand what wifi has to do with it.  The characterization tool doesn't need wifi.  The tool even has ["deploy project"](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-characterization/deploying-project.html) built in.

**Comment by jasondaming** [comment]
Did this make sense?  Do you have additional questions?

**Comment by mendax1234** [comment]
Sorry for replying so late since l have had a test recently.
> I think instead of one continuous path you would want to separate it into multiple paths. 

But , how many paths should l seperate it ? Is there any requirements? Or , it just depend on my mood?

**Comment by mendax1234** [comment]
> In the future please use Github to post code as it is much easier for us to look at.

Since the repository is now private , l will public it maybe next year when the 2022 season is over. Sorry for that.

> You mentioned above that you were modifying the .json files. How are you modifying them? Why are you modifying them? Does it load fine with an unmodified file?

l have found that the problem is in the photonlib.json. Since l can't install photonlib from online . So l download it directly and copy it to the venderdeps. However , it seems that the code built well , but the auto can't work . So l copy another photonlib.json which l have successfully downloaded with WPILIB 2021.3.1 in May to the venderdeps and now it works well , nothing goes wrong. 

- Besides , l also want to make sure that do l have to use frc-characterization tool to characterize my swerve? Since the PIDController parameters need to be tuned.

**Comment by jasondaming** [comment]
frc-characterization is/was deprecated.  We have replaced it with [SysID](https://github.com/wpilibsuite/sysid) which is much more user friendly.  I am not sure exactly what you are looking to tune for your swerve but it should help.

**Comment by mendax1234** [comment]
Can l use it now？ Or do l need to wait until the 2022 version is launched？

**Comment by jasondaming** [comment]
Yes it is fully functional now and will ship as part of the 2022 season.  You can use it now via either the instructions linked or as part of the FRC beta testing!

**Comment by mendax1234** [comment]
Hello , l have run into a problem recently. We draw a straight line in Pathweaver and load it successfully. However , when l enable the autonomous mode , the swerve will rotate but l don't let it rotate . It's strange.

![image](https://user-images.githubusercontent.com/62934294/140335431-626195ae-a99a-432b-a65f-037f7ed2ee54.png)

**Comment by jasondaming** [comment]
Lets keep issues separate so they are trackable instead of just keep adding onto this issue.

I don't understand what "the swerve will rotate but l don't let it rotate" means.  Before using PathWeaver you should be verifying that you can run simple trajectories like this one, have you done that?

**Comment by mendax1234** [comment]
> Lets keep issues separate so they are trackable instead of just keep adding onto this issue.
> 
> I don't understand what "the swerve will rotate but l don't let it rotate" means. Before using PathWeaver you should be verifying that you can run simple trajectories like this one, have you done that?

l have tested it . l don't change any parameters , and draw 3 trajectories. It seems that it works well (But does it mean that l don't need to test the parameters?) . However , when it finished one trajectory, it will stop suddenly and then go another trajectory. I would like it to be continuous. Should l draw it in one trajectory? 

Besides , how to create a PathGroup?
