### ISSUE TITLE
PathDisplayController should provide edit method

### ISSUE THREAD

**Issue by SilentWanderer** [wpilibsuite/PathWeaver#45]
**Is your feature request related to a problem? Please describe.**  
Without an edit method in `PathDisplayController`, Paths must be manually removed, changed, then added back.

**Describe the solution you'd like**  
Adding an edit method in `PathDisplayController` that takes in a Path name and a new Path to replace the old one (Like the `put` method in a `Map`)

**Comment by SilentWanderer** [comment]
This is not a feature request and does not pertain to user interactions or any external functionality

**Comment by gftabor** [comment]
So looking through PathDisplayController there is an observablelist
`  private final ObservableList<Path> pathList = FXCollections.observableArrayList();
`
Any edits to the list are automatically updated on the display because of this function
```
  private void setupPathList() {
    pathList.addListener((ListChangeListener<Path>) change -> {
      while (change.next()) {
        for (Object o : change.getRemoved()) {
          Path path = (Path) o;
          removePathFromPane(path);
        }
        for (Object o : change.getAddedSubList()) {
          Path path = (Path) o;
          addPathToPane(path);
        }
      }
    });
  }
```
You can add a new path by filename
```
  /**
   * Add path to Controller.
   *
   * @param fileLocations Current working directory
   * @param fileName      Name of path file inside directory
   */
  public void addPath(String fileLocations, String fileName) {
```
Or remove all paths from the display
```
  /**
   * Remove all paths from Controller.
   */
  public void removeAllPath() {
    pathList.clear();
  }
```

The 3 ways to edit a path that is being displayed all happen with the pathDisplayController without being

> manually removed, changed, then added back.
They are all done as drag events
```
drawPane.setOnDragOver(event -> {
      Dragboard dragboard = event.getDragboard();
      Waypoint wp = Waypoint.currentWaypoint;
      if (dragboard.hasContent(DataFormats.WAYPOINT)) {
        handleWaypointDrag(event, wp);
      } else if (dragboard.hasContent(DataFormats.CONTROL_VECTOR)) {
        handleVectorDrag(event, wp);
      } else if (dragboard.hasContent(DataFormats.SPLINE)) {
        handleSplineDrag(event, wp);
      }
    });
```

Finally if you want to edit a path directly without a drag event you can access the path object you can move them all manually with
`    path.getEnd().setX(); `
for example

**Comment by gftabor** [comment]
Nope
